service: issrecipechatbot

plugins:
    - serverless-dotenv-plugin
    - serverless-offline

package:
    exclude:
        - node_modules/**
    excludeDevDependencies: true

provider:
    name: aws
    runtime: nodejs12.x
    lambdaHashingVersion: 20201221
    stage: ${opt:stage, 'dev'}
    region: ${self:custom.vars.region, 'ap-southeast-2'}
    environment:
        STAGE: ${self:provider.stage}
        # BOT_TOKEN: ${self:custom.namePrefix}

layers:
    issrecipe:
        path: src/layer
        name: ${self:service}-Layer
        description: 'Node.js dependencies'

functions:
    bothandler:
        name: ${self:service}-bot-handler
        handler: src/controllers/v1_0/bot/handler.handler
        layers:
            - { Ref: IssrecipeLambdaLayer }
        events:
            - http:
                  path: bot/handler
                  method: post
                  cors: true
    # ngrok:
    #   name: ${self:custom.namePrefix}-ngrok-start
    #   handler: src/controllers/v1_0/ngrok/start.handler
    #   events:
    #     - http:
    #         path: ngrok/start
    #         method: get
    #         cors: true
